### PR TITLE
Dip 36

### PR DESCRIPTION
**Pull request by jiadongwang**

### CODE REVIEW

**Comment by tkralphs** [comment]
What is this?

**Comment by jiadongwang** [comment]
hmm. those are a bunch of stuff, including some code improvement, ms vs 13 solution files, and some code from my old svn branch, which is never merged to master.

**Comment by jiadongwang** [comment]
probably I need to put some more granular stuff per PR

**Comment by tkralphs** [comment]
Umm, yes.

**Comment by tkralphs** [comment]
Especially since this seems to include some of the same commits that are in #16!

**Comment by jiadongwang** [comment]
it might be easier just to merge everything in my master to this master since these changes are not involved in major functionalities. It passed testing. we can merge individual branches from then on. I have to rebase each branch on coin-or/Dip/master to get a clear difference of each branch against master.

**Pull request closed without merging**
