### PR TITLE
Dip-7: add some files to enable Dip built with vs 2013

### PR DESCRIPTION
**Pull request by jiadongwang**
let us make a try

### CODE REVIEW

**Comment by jiadongwang** [comment]
why not merge this one first , so that the following individual branches can be merged incrementally?

**Comment by tkralphs** [comment]
I will do that as soon as I can commit to moving to git permanently.

**Comment by jiadongwang** [comment]
thanks. It would be very helpful to accelerate things up.

**Comment by svigerske** [comment]
The Dip repository has been recreated. Please recreate this pull request w.r.t. coin-or/Dip. Sorry for the inconvenience.

**Pull request closed without merging**
